### ISSUE TITLE
Raspberry compatibility

### ISSUE THREAD

**Issue by CarloCattano** [CarloCattano/PopularSynth#6]
just checking and I can't seem to successfully install it on the pi after the new updates.
will check it this evening, I'll bring the pi with me

@rp3:~/PopularSynth $ npm start

> PopularSynth@0.0.1 start /home/pi/PopularSynth
> node dist/server.js

events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (net.js:1329:19)
    at listenInCluster (net.js:1387:12)
    at Server.listen (net.js:1475:7)
    at Object.<anonymous> (/home/pi/PopularSynth/dist/server.js:1:1398)
    at r (/home/pi/PopularSynth/dist/server.js:1:172)
    at /home/pi/PopularSynth/dist/server.js:1:579
    at Object.<anonymous> (/home/pi/PopularSynth/dist/server.js:1:588)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
Emitted 'error' event at:
    at emitErrorNT (net.js:1366:8)
    at process._tickCallback (internal/process/next_tick.js:178:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:697:11)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! PopularSynth@0.0.1 start: `node dist/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the PopularSynth@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

@charlesfleche

**Comment by charlesfleche** [comment]
You try to open the server port 80, which is reserver on Linux. You
probably have it opened on your Windows setup, but on Linux you need either
admin privileges or open on another port. I've added a variable environment
for exactly this purpose : try to run

```
$ NODE_PORT=8080 npm start
```

and then access `http://[ip]:8080`
